### ISSUE TITLE
凸链的结果有点诡异

### ISSUE THREAD

**Issue by cain4318** [songzy12/LECP#18]
animation 分支下
：打开testCase2
dcel排序，点5，点3的结果好奇怪，输出的log也好奇怪（貌似in out边都存了两次）
testCase的结果貌似是比较正常的

@songzy12

**Comment by songzy12** [comment]
in out 的边存的应该是正确的。
原因在于 out_edges 遍历时也应该为逆序。
可见图计算结束后每个点所存储的 in_edges, out_edges 均为逆时针顺序。
最长凸链生成时的处理顺序均为顺时针。
