### ISSUE TITLE
lecp.cpp中添加变量记录总的点数

### ISSUE THREAD

**Issue by cain4318** [songzy12/LECP#22]
每次点击添加新点时，更新一下这个值。
读取文件的时候，设置一下这个值
随机生成点时，设置一下这个值

**Comment by cain4318** [comment]
或者现在有哪个类似可替代的变量，例如存屏幕点的数组的长度

**Comment by songzy12** [comment]
恩。。你是指 lecp_doc->paint_widget_->points.size() ? @cain4318

**Comment by cain4318** [comment]
ok，我试一下，现在的poly2show也有paint_widget_的指针

**Comment by cain4318** [comment]
可以了
