### ISSUE TITLE
生成随机点时会生成到屏幕之外

### ISSUE THREAD

**Issue by songzy12** [songzy12/LECP#23]
比如刚开始时都生成在屏幕之类（个数选10个即可），然后点演示按钮时因为高度上多了一栏会导致有些点偏移到屏幕之外

**Comment by songzy12** [comment]
不太记得这部分是谁写的，大概的解决办法可以是在生成点坐标时比如说上下左右留一段空白出来（避免生成的点落在边界上或者因为后面的操作产生位移出边界）
@XYZ916829 @cain4318

**Comment by XYZ-916** [comment]
上下左右和前后都向内回收了5个像素的距离，不知道还会不会这种错误。（还没有push，回头待测试）

**Comment by songzy12** [comment]
现在比如点了随机点生成10个点之后，接着再点随机点生成10个点。表现是会在上一轮生成的点上把各个标签加10。期望是先清空，然后重新生成。

**Comment by songzy12** [comment]
以及下方的 5 个像素点看起来不是很够？（我觉得至少应该是工具栏的高度吧）

**Comment by XYZ-916** [comment]
工具栏高度并不知道怎么获取，只能先将offset设置的高一些了，目前为20

**Comment by XYZ-916** [comment]
随机点生成时将之前屏幕上点清空。offset改为40，目测没有在窗口外面的点了。
