### ISSUE TITLE
如果用户没有点极角排序就直接点了生成可见图（不重要）

### ISSUE THREAD

**Issue by songzy12** [songzy12/LECP#25]
最好可以首先帮他自动执行极角排序，不然程序会崩溃
检查是否已进行极角排序可通过比较  mesh->sortedVector.size() 是否等于 屏幕上点的个数。

**Comment by cain4318** [comment]
改啦，在startShowSlot分模式演示动画之前先进行极角排序

**Comment by songzy12** [comment]
比如 testCase5，如果我不进行任何操作点 VG 的动画演示，当前的行为看起来是这样：第一次点击时弹出了 DCEL 排序结束时的对话框，然后没有后续行为。第二次点击时也会弹出 DCEL 排序结束时的对话框，然后开始正常演示。
@cain4318

**Comment by cain4318** [comment]
那个是因为有一句代码放错位置了，已经搞定啦 @songzy12

**Comment by songzy12** [comment]
如果有时间希望比如说如果已经进行过排序的话，不需要再重复执行这一步。
检查是否已进行极角排序可通过比较 mesh->sortedVector.size() 是否等于 屏幕上点的个数。
