### ISSUE TITLE
“操作”->"DCEL" 弹出窗口关闭后会有闪过的窗口

### ISSUE THREAD

**Issue by songzy12** [songzy12/LECP#27]
比如 加载 testCase，“操作”，“DCEL”

**Comment by cain4318** [comment]
后期会删掉菜单栏的，只保工具栏，别的操作会有闪过的窗口吗

**Comment by songzy12** [comment]
恩应该跟菜单栏无关，就是比如在演示中直接选 "VG" 它会先进行排序嘛，那时也会有闪过的窗口 @cain4318

**Comment by XYZ-916** [comment]
要不我把DCEL弹窗注释掉？当时直线为了看DCEL进行极角排序的运行时间，目前看来暂时不需要，我先注释掉吧。

**Comment by songzy12** [comment]
恩在那个显示运行时间的弹窗之后有另外一个一闪而过的弹窗 发自网易邮箱大师 在2017年05月28日 14:26，XYZ 写道： 要不我把DCEL弹窗注释掉？当时直线为了看DCEL进行极角排序的运行时间，目前看来暂时不需要，我先注释掉吧。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
