### ISSUE TITLE
请大家检查当前动画演示和界面存在的问题

### ISSUE THREAD

**Issue by cain4318** [songzy12/LECP#29]
如题，请大家把发现的有关界面，动画控制，动画演示存在的问题记录在此，我将逐一解决

**Comment by songzy12** [comment]
在随机生成点（比如10个）后，然后选择单点演示，似乎不太正常（并不会进行演示） @cain4318

**Comment by XYZ-916** [comment]
屏幕上点击生成若干个点之后，选择单点演示，只勾选sort,演示时貌似并没有显示极角排序的动画。 @cain4318

**Comment by cain4318** [comment]
问题1：在随机生成点（比如10个）后，然后选择单点演示，似乎不太正常（并不会进行演示） 

````````````````````````````````````````
	case singlePoint:
		poly2show->clear();
		int kernalSelected = getSortedIndex(pointSpinBox->value());
		trans2Poly(kernalSelected);
		break;
	}
`````````````````````````````````````
随机点-》单点演示时，没有反应是因为得到的sortedIndex=-1，可能时随机点添加的时候有些结构没更新？ @ @ @songzy12 @XYZ916829

**Comment by cain4318** [comment]
问题2：屏幕上点击生成若干个点之后，选择单点演示，只勾选sort,演示时貌似并没有显示极角排序的动画。

只勾选sort，只逆时针显示一下点和starpoly的边，要勾选dcel才显示极角排序的dcel动画 @XYZ916829

**Comment by songzy12** [comment]
比如只勾选 sort 和 decl，现在看起来也会顺便演示后面的动画？

**Comment by cain4318** [comment]
问题4：allpoints时演示两次貌似会从右向左，再从左向右
