### ISSUE TITLE
重构：DCEL 维护时可封装的操作（不重要）

### ISSUE THREAD

**Issue by songzy12** [songzy12/LECP#5]
1. splitHalfEdge(Vertex* v, HalfEdge* e)：使用一个新的 v 来将 e 分为两段
      添加 v, 添加两条新的半边，修改旧的两条半边的 origin 
2. splitFace(Vertex* u, Vertex *v, HalfEdge *e_u, HalfEdge *e_v)：连接两个已有 u, v
      添加两个新的半边

**Comment by XYZ-916** [comment]
Two methods : HalfEdge* splitEdge(HalfEdge* half_edge,Vertex* vertex); 
void connectTwoNewVertices(HalfEdge* h1,HalfEdge* h2,LECP_Point *point);
in mesh
