### ISSUE TITLE
极角排序时用户输入的点 x 可能相同

### ISSUE THREAD

**Issue by songzy12** [songzy12/LECP#6]
用户输入的两个点 x 坐标相同，导致 dual graph 中两条直线无交点

**Comment by songzy12** [comment]
参考 <https://dsa.cs.tsinghua.edu.cn/~deng/cg/project/2015s/2015s-a.pdf>

**Comment by songzy12** [comment]
按 x 从小到大排序时同时按 y 从小到大排序，这样 只需要将已处理过的 x 相同的接在 list 最后即可

**Comment by XYZ-916** [comment]
The order of input points is correct(first sorted by x ,from small to large,when x is same, y from small to large)

**Comment by XYZ-916** [comment]
solved
